import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <footer>
          <h4 className="flex min-h-screen flex-col items-center justify-between p-24">พัฒนาโดย ชาติ</h4>
        </footer>
        </body>
    </html>
  )
}
